### ISSUE TITLE
I cannot open settings and log into program

### ISSUE THREAD

**Issue by michaldybczak** [jplsek/puush-qt#2]
Because of that, the whole app became unusable. Can it be caused by the update to qt5-base 5.8? I heard that this version is quite buggy (and 5.9 is faulty as well) and I experience some bugs in other qt apps since then. Or maybe that's just a bug in the program that showed in the latest update that showed in 14.05.2017 in AUR?

**Comment by jplsek** [comment]
I'm assuming that the app itself still launches, and the system tray shows up, but clicking Settings does nothing.

This most likely is a dependency issue. If you try to launch from the command line `puush-qt`, debug output should show up (I hope).

When you try to open the settings, the terminal should say what's missing (including some get-history spam, which I should probably look into). ATM, I can't create a fresh Arch install to test this. Reply back with attachment of the output, or just paste what is missing.

It could also have to do with updating qt when originally compiling with an older version of qt, and that's because of the global hotkey system I'm using. If that's the case, then I have a bigger problem that I think I should fix... (hopefully this is not the case.)

In the mean time, you can manually "log in" by getting your API key from [puush](https://puush.me/account/settings), then in `~/.config/puush-qt/puush-qt.conf`, set "key" equal to the api key (like `key=123abcxxx`).

Sorry for the app-breaking bugs. I haven't been able to extensively test a non-development arch environment.

Thanks!

**Comment by jplsek** [comment]
Ehh, never mind. I just set up an arch vm and got it settled. I've updated the readme and the aur package.

I did find dependency issues, so install these packages: `qt5-declarative qt5-quickcontrols qt5-quickcontrols2`

Reply back if that worked or didn't work!

**Comment by michaldybczak** [comment]
Thanks! It works now :).
I updated the new version from AUR and it installed qt5-quickcontrols2 for me (rest was already in the system) and now it opens settings window and I was able to log in.

The only things I noticed being grayed out are: "play sound" and "screen capture quality", but that's not a big problem. I always used default settings.

Again, thanks, problem solved :).
